name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python -m unittest discover -s . -p '*_test.py'

  docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy Documentation
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        cd docs
        git init
        git remote add origin https://github.com/Massooma/projet-ci.git
        git checkout -b gh-pages
        git add .
        git commit -m "Update documentation"
        git push --force --set-upstream origin gh-page
